# You have to configure this ###################################################
title: Lieblings-Plätzchen
# You should configure this ####################################################
url: http://localhost:4000
url: #http://www.lieblings-plaetzchen.com
subtitle: Podcast
description: Jana begleitet pro Episode ein_e Gäst_in zu deren Lieblings-Plätzchen (meistens in Wien), um mehr über Person und Plätzchen zu erfahren und am Ende Lieblings-Plätzchen zu essen. Letzteres nicht nur wegen des Wortspiels, sondern wegen der Internetheimat der Gastgeberin, dem Foodblog Zuckerbäckerei.
author: Jana Wiese
email: jana@lieblings-plaetzchen.com
keywords: [podcast, wien, vienna, österreich, austria]
itunes_categories: [Society &amp; Culture]
additional_feeds:
   itunes: https://itunes.apple.com/de/podcast/lieblings-platzchen/id1150947265
#   torrent_m4a: http://bitlove.org/example_user/example_podcast_m4a/feed
#   torrent_mp3: http://bitlove.org/example_user/example_podcast_mp3/feed
episodes_per_feed_page: 999
## podlove-web-palyer ##########################################################
poster: /img/lieblings-plaetzchen-cover360.jpg
alwaysShowHours: true
startVolume: 0.8
width: auto
summaryVisible: true
timecontrolsVisible: false
chaptersVisible: true
sharebuttonsVisible: false
## Rsync Deploy config #########################################################
### Be sure your public key is listed in your server's ~/.ssh/authorized_keys
### file.
#ssh_host: user@host.org
#ssh_port: 22
document_root: /
rsync_delete: true
# You can configure this #######################################################
twitter_nick: liebplaetzchen
language: de
explicit: 'no'  # 'yes'/'no'/clean
license: CC BY NC SA 4.0
## Flattr ######################################################################
flattr_uid: liebplaetzchen # Flattr will not be used unless this is set
flattr_button: compact # compact | default
flattr_mode: auto # auto | manual(default)
flattr_popout:  1 # 1 | 0 (show popout when hovering mouse over button)
flattr_language: en_GB # available languages - https://api.flattr.com/rest/v2/languages.txt
flattr_category: audio # available categories - https://api.flattr.com/rest/v2/categories.txt
## Disqus comments #############################################################
disqus_shortname: lieblings-plaetzchen # Disqus will not be used unless this is set
disqus_developer: 0 # 1 / 0
## Itunes link ###########################################################
## itunes_url: "https://itunes.apple.com/at/podcast/myname/id#myid#"
## Collections - Sammlung 06.08.2016###
collections:
  sammlungen:
    output: true
    layout: sammlung
